### PR TITLE
Automerge Dependabot PRs with passing automation

### PR DESCRIPTION
**Pull request by janelletavares**
# Description

Automate closing more dependency PRs

Related to https://github.com/meroxa/engineering/issues/51

## Type of change

Please delete options that are not relevant.

- [x] New feature
- [ ] Bug fix
- [ ] Refactor
- [ ] Documentation

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Unit Tests
- [ ] Manual Tests
- [ ] Deployed to staging

## Demo

| before | after |
|--------|-------|
|||

# Additional references

*Any additional links (if appropriate)*

### CODE REVIEW

**Comment by janelletavares** [comment]
can we double check that this repo doesn't allow PRs to be merged unless they pass all test steps?

**Review by jayjayjpg — APPROVED** [review]
This reads great, thank you for the super quick update! :sparkles:

**Comment by jayjayjpg** [comment]
> can we double check that this repo doesn't allow PRs to be merged unless they pass all test steps?

@janelletavares I don't have admin access to this repo to make the config change myself, but hopefully someone else can help out!

**Comment by ericcheatham** [comment]
> can we double check that this repo doesn't allow PRs to be merged unless they pass all test steps?

I can do that. Will update when it is completed.

**Pull request merged**
